Add instructions
w3c/vr-workshop pull request #40
Opened 2016-10-11 16:35 UTC by anssiko

@dontcallmedom @cvan let's use this PR to hash out the instructions, see what should be included. Perhaps this should be on a separate page, but let's get the content ready first.

Preview: https://rawgit.com/w3c/vr-workshop/instructions/schedule.html

2016-10-11 20:04 UTC, cvan requested changes
👍 looks great. just some minor changes.

I especially like what you did with the colour-coding and legend. easy to read.

2016-10-11 20:04 UTC, cvan commented on schedule.html
> +          Discussion topic (30-60 mins) starts off with 3-4 5-minute <a href=
would change to `three or four 5-minute`

2016-10-11 20:04 UTC, cvan commented on schedule.html
> +          Discussion topic (30-60 mins) starts off with 3-4 5-minute <a href=
`mins` and `minute` - should be consistent

2016-10-11 20:04 UTC, cvan commented on schedule.html
> +          session schedule grid is identified and built collaboratively by the
would remove word `grid`

2016-10-11 20:04 UTC, cvan commented on schedule.html
> +          participants in the course of the workshop. Each groups to provide a
`groups` to `group is`

2016-10-11 20:04 UTC, cvan commented on schedule.html
> +        channel</a> is used for plenary and <a href="#lightning">lightning
link to `#plenary` as well?

2016-10-11 20:04 UTC, cvan commented on schedule.html
> +        discussions. These notes will be made public. TODO: add instructions
perhaps make `TODO` a comment instead?

2016-10-11 20:04 UTC, cvan commented on style.css
> +span.lightning, span.plenary, span.breakout, span.panel {
might as well create a common class for these

2016-10-11 20:04 UTC, cvan commented on style.css
> +  content: "plenary"
`;`

2016-10-11 20:04 UTC, cvan commented on schedule.html
> +          speakers nominated in advance. Lightning talks are followed by group
this is mentioned already [above](https://github.com/w3c/vr-workshop/pull/40/files#diff-0953deb6637fd0edbb59e4e408606954R371), but I suppose it's fine to repeat it so people don't miss

2016-10-11 20:04 UTC, cvan commented on schedule.html
> +          <a href="https://surma.link/things/reading-specs/">How to read web
good link to add 👍

2016-10-11 20:07 UTC, cvan commented on schedule.html
> +          <span class="plenary" id="plenary"></span>
seems like it'd be better to just do

```html
<dt class="format format-plenary" id="plenary">
  Plenary
</dt>
```

2016-10-11 20:16 UTC, cvan commented on style.css
> +  font-size: 67%;
this looks good in the schedule, but for the legend, the font-size could be bumped up for legibility and some margins could be added I think.

<img width="1153" alt="screen shot 2016-10-11 at 1 12 33 pm" src="https://cloud.githubusercontent.com/assets/203725/19286901/67601718-8fb4-11e6-8bdb-55fe8aedfda3.png">

<img width="1154" alt="screen shot 2016-10-11 at 1 10 31 pm" src="https://cloud.githubusercontent.com/assets/203725/19286886/558eab62-8fb4-11e6-8c0f-c4da2ced918b.png">


here are the styles I used:

```css
dt.format {
  box-shadow: .3em .3em 0 rgba(0,0,0,.1);
  font-size: 1rem;
  font-weight: 600;
  margin: 0 5px 15px 0;
  padding: 8px 10px;
}
```

2016-10-11 20:17 UTC, cvan commented on style.css
> +  content: "lightning";
IMO, we should just add normal text content

2016-10-11 20:17 UTC, cvan commented on style.css
> +  content: "lightning";
(mostly for copy+paste reasons and accessibility)

2016-10-12 09:05 UTC, dontcallmedom commented on schedule.html
> +          Discussion topic (30-60 mins) starts off with 3-4 5-minute <a href=
addressed

2016-10-12 09:05 UTC, dontcallmedom commented on schedule.html
> +          session schedule grid is identified and built collaboratively by the
addressed

2016-10-12 09:06 UTC, dontcallmedom commented on schedule.html
> +        channel</a> is used for plenary and <a href="#lightning">lightning
addressed

2016-10-12 09:06 UTC, dontcallmedom commented on style.css
> +  font-size: 67%;
addressed

2016-10-12 09:06 UTC, dontcallmedom commented on style.css
> +  content: "lightning";
addressed

2016-10-12 12:38 UTC, dontcallmedom commented
I've changed the markup for the schedule to allow to add more detailed informations (speakers, related papers, links to slides) in collapsible form

2016-10-12 12:40 UTC, anssiko commented
@dontcallmedom @cvan thanks for your review comments and commits!

I think we're now ready to go live with these "instructions v1" (can add more instructions later as needed).

@dontcallmedom WDYT?

2016-10-12 12:42 UTC, dontcallmedom commented
@anssiko I'll merge the pre-markup changes to gh-pages and keep that PR open for further iterations

2016-10-12 12:42 UTC, anssiko commented
@dontcallmedom Stop press. I think https://github.com/w3c/vr-workshop/pull/40/commits/6fc2dd30b79c314aa9da6b5144cbdd5a3f7dc24d broke the CSS?

2016-10-12 12:43 UTC, anssiko commented
See https://rawgit.com/w3c/vr-workshop/instructions/schedule.html

2016-10-12 12:45 UTC, dontcallmedom commented
can you be more specific on "broke the CSS" @anssiko ?
(note that as described above, I've merged the clean version to gh-pages)

2016-10-12 12:50 UTC, anssiko commented
OK, now I see you did not merge the experimental collapsable items feature yet -- good.

Let's keep iterating that in this PR and integrate the details as well.

2016-10-12 13:25 UTC, dontcallmedom commented
oh, I guess the rendering is very different in chrome and in firefox; I now understand better the broken style comment :)

2016-10-12 13:55 UTC, dontcallmedom commented
ok, apparently, [`summary` cannot be used as a target for `display:flex` in Chrome](http://stackoverflow.com/questions/30650471/display-flex-doesnt-work-on-summary-tags-in-chrome), will fix

2016-10-12 14:53 UTC, anssiko commented on schedule.html
> +        To join the workshop Slash team:
s/Slash/Slack/

2016-10-12 18:43 UTC, anssiko commented
Cherry-picking https://github.com/w3c/vr-workshop/commit/defa3619b97a5d077d810fa95c5b1c114852a710 was too painful, so we have a conflict to resolve.

2016-10-12 19:13 UTC, cvan commented
do you want me to manually resolve + merge this?

2016-10-12 19:22 UTC, anssiko commented
@cvan if you can resolve the conflict introduced by https://github.com/w3c/vr-workshop/commit/defa3619b97a5d077d810fa95c5b1c114852a710 that'd be awesome. I wouldn't yet merge this branch into gh-pages since there are bugs, and @dontcallmedom indicated he's planning to fix them.

2016-10-12 19:50 UTC, cvan commented on schedule.html
> +        To join the workshop Slash team:
fixed

2016-10-12 20:14 UTC, cvan approved these changes

2016-10-12 20:51 UTC, anssiko commented
To accommodate Philip Rosedale I switched two slots. @cvan It'd be great if you could integrate https://github.com/w3c/vr-workshop/commit/ca7a642c07794db0e2b6c8b50f953a7d7226e65f to this branch.

2016-10-12 22:27 UTC, cvan commented
closing in favour of new upcoming PR

2016-10-12 22:27 UTC, closed without merging